# Automatically generated by Pynguin.
import controller as module0


def test_case_0():
    try:
        var0 = module0.Controller()
        assert var0 is not None
        var1 = var0.print_pdf()
    except BaseException:
        pass


def test_case_1():
    try:
        var0 = module0.Controller()
        assert var0 is not None
        var1 = var0.print_json()
    except BaseException:
        pass
