# Automatically generated by Pynguin.
import view as module0


def test_case_0():
    try:
        var0 = -1568.28
        var1 = module0.View()
        assert var1 is not None
        var2 = var1.get_option(var0)
    except BaseException:
        pass
