# Automatically generated by Pynguin.
import view as module0


def test_case_0():
    var0 = module0.View()
    assert var0 is not None
    var1 = var0.create_user()


def test_case_1():
    var0 = module0.View()
    assert var0 is not None
    var1 = var0.create_user()
    var2 = [var0, var1]
    var3 = var0.get_option(var2)


def test_case_2():
    var0 = {}
    var1 = module0.View()
    assert var1 is not None
    var2 = var1.get_option(var0)


def test_case_3():
    var0 = module0.View()
    assert var0 is not None


def test_case_4():
    var0 = module0.View()
    assert var0 is not None
    var1 = module0.View()
    assert var1 is not None
    var2 = var1.create_user()
    var3 = [var1, var2]
    var4 = var1.get_option(var3)
    var5 = {}
    var6 = module0.View()
    var7 = var6.get_option(var5)
    var8 = var0.create_user()


def test_case_5():
    var0 = {}
    var1 = module0.View()
    assert var1 is not None
    var2 = var1.get_option(var0)
    var3 = module0.View()
    var4 = var3.create_user()
    var5 = [var3, var4]
    var6 = var3.get_option(var5)
    var7 = {var2, var1, var1}
    var8 = var3.set_temp_metrics(var7)


def test_case_6():
    var0 = module0.View()
    assert var0 is not None
    var1 = var0.create_user()
    var2 = {}
    var3 = module0.View()
    var4 = var3.get_option(var2)
    var5 = module0.View()
    var6 = var5.create_user()
    var7 = [var5, var6]
    var8 = var5.get_option(var7)
    var9 = {var4, var3, var3}
    var10 = var5.set_temp_metrics(var9)
    var11 = {}
    var12 = module0.View()
    var13 = var12.get_option(var11)
    var14 = module0.View()
    var15 = module0.View()
    var16 = module0.View()
    var17 = var16.create_user()
    var18 = [var16, var17]
    var19 = var16.get_option(var18)
    var20 = {}
    var21 = module0.View()
    var22 = var21.get_option(var20)
    var23 = var15.create_user()
    var24 = var0.get_credentials()
