# Automatically generated by Pynguin.
import controller as module0


def test_case_0():
    var0 = module0.Controller()
    assert var0 is not None
    var1 = var0.check_auth()


def test_case_1():
    var0 = module0.Controller()
    assert var0 is not None
    var1 = var0.check_auth()
    var2 = var0.print_pdf()


def test_case_2():
    var0 = module0.Controller()
    assert var0 is not None
    var1 = var0.check_auth()
    var2 = var0.print_pdf()
    var3 = var0.get_env_score()


def test_case_3():
    var0 = module0.Controller()
    assert var0 is not None
    var1 = var0.check_auth()
    var2 = var0.print_pdf()
    var3 = module0.Controller()
    var4 = var3.check_auth()
    var5 = module0.Controller()


def test_case_4():
    var0 = module0.Controller()
    assert var0 is not None
    var1 = var0.check_auth()
    var2 = var0.print_pdf()
    var3 = module0.Controller()
    var4 = var3.check_auth()
    var5 = module0.Controller()
    var6 = var5.start()


def test_case_5():
    var0 = module0.Controller()
    assert var0 is not None
    var1 = var0.check_auth()
    var2 = var0.print_pdf()
    var3 = var0.get_env_score()
    var4 = module0.Controller()
    var5 = var4.check_auth()
    var6 = var4.print_pdf()
    var7 = module0.Controller()
    var8 = var7.check_auth()
    var9 = module0.Controller()
    var10 = var9.start()
    var11 = module0.Controller()
    var12 = var11.check_auth()
    var13 = module0.Controller()
    var14 = var13.check_auth()
    var15 = var13.print_pdf()
    var16 = module0.Controller()
    var17 = var16.check_auth()
    var18 = module0.Controller()
    var19 = var0.gui_loop()
